# +----------------------------------------------------------------------------------------------+
# |                                                                                              |
# |                                          Build Tickets                                       |
# |                                                                                              |
# |                          Website: https://github.com/Zffu/BuildTickets                       |
# |                                                                                              |
# |                                         Author: Zffu, Diph                                   |
# |                                                                                              |
# +----------------------------------------------------------------------------------------------+

# The version of the config. Used to make sure that the config is valid
version: 2

############################################################
# +------------------------------------------------------+ #
# |                 Database                             | #
# +------------------------------------------------------+ #
############################################################

# Available modes:
# - sqlite: SQL Database in a file
# - crimson: CrimsonDB Database (local)
# - none: No data saving & loading
storage-mode: sqlite

# Only required if your database type is not sqlite or crimson.
database-url: ""

# Only required if your database type is not sqlite or crimson.
database-credentials: ""

# Should the players be able to change the plugin language for them?
allow-players-to-choose-custom-language: true

# The default language used by the server. Use the https://github.com/BuildTickets/Translations to check which languages are supported.
default-language: "en"


############################################################
# +------------------------------------------------------+ #
# |                 Build Mode Feature                   | #
# +------------------------------------------------------+ #
############################################################

build-mode:
  enabled: true


############################################################
# +------------------------------------------------------+ #
# |                 Builder Chat Feature                 | #
# +------------------------------------------------------+ #
############################################################

build-chat:
  enabled: true


############################################################
# +------------------------------------------------------+ #
# |                 Building Physics Feature             | #
# +------------------------------------------------------+ #
############################################################

build-physics:
  enabled: true

############################################################
# +------------------------------------------------------+ #
# |                 Head Giver Feature                   | #
# +------------------------------------------------------+ #
############################################################
head-giver:
  enabled: true

############################################################
# +------------------------------------------------------+ #
# |                 General Ticket Settings              | #
# +------------------------------------------------------+ #
############################################################

tickets:
  # Enabling this ticket will make it so builders and the owner of tickets can modify the ticket's settings without requiring the permissions
  smart-ticket-permissions: true
  webhook-url: ""

############################################################
# +------------------------------------------------------+ #
# |                 General Permissions                  | #
# +------------------------------------------------------+ #
############################################################
# To disable a permission, leave the field blank
help-message-permission: buildtickets.general.help
build-mode-toggle-permission: buildmode.toggle
build-physics-toggle-permission: buildphysics.toggle
head-giver-permission: headgiver.use

############################################################
# +------------------------------------------------------+ #
# |                 Ticket Permissions                   | #
# +------------------------------------------------------+ #
############################################################
open-ticket-gui-permission: buildtickets.tickets.gui
create-ticket-permission: buildtickets.tickets.create


############################################################
# +------------------------------------------------------+ #
# |                 Ticket Permissions (Self)            | #
# +------------------------------------------------------+ #
############################################################
change-ticket-priority-permission: buildtickets.tickets.change_priority
join-ticket-permission: buildtickets.tickets.join
join-without-help-permission: buildtickets.tickets.join_without_help
request-help-permission: buildtickets.tickets.request_help
ticket-mark-as-complete-permission: buildtickets.tickets.complete.mark
ticket-confirm-as-complete-permission: buildtickets.tickets.complete.confirm
ticket-change-reason-permission: buildtickets.tickets.change_reason
ticket-leave-permission: buildtickets.tickets.leave
open-ticket-viewer-permission: buildtickets.viewer.open


############################################################
# +------------------------------------------------------+ #
# |                 Ticket Permissions (Other)           | #
# +------------------------------------------------------+ #
############################################################
change-ticket-priority-other-permission: buildtickets.tickets.other.change_priority
join-ticket-other-permission: buildtickets.tickets.other.join
join-without-help-other-permission: buildtickets.tickets.other.join_without_help
request-help-other-permission: buildtickets.tickets.other.request_help
ticket-mark-as-complete-other-permission: buildtickets.tickets.other.complete.mark
ticket-confirm-as-complete-other-permission: buildtickets.tickets.other.complete.confirm
ticket-change-reason-other-permission: buildtickets.tickets.other.change_reason
ticket-leave-other-permission: buildtickets.tickets.other.leave
open-ticket-viewer-other-permission: buildtickets.viewer.other.open

############################################################
# +------------------------------------------------------+ #
# |                 Ticket Permissions (Panel)           | #
# +------------------------------------------------------+ #
############################################################
open-ticket-panel-permission: buildtickets.panel.open
player-stats-panel-permission: buildtickets.panel.player_stats
active-tickets-panel-permission: buildtickets.panel.active_tickets
