name: BuildTickets
version: '${project.version}'
main: net.zffu.buildtickets.BuildTicketsPlugin
api-version: '1.20'
commands:
  buildtickets:
    description: The main command of the plugin.
    aliases: [bt, btickets, bticket, buildticket]
